SELECT DATA,RIGHT(CODGERENCIAL,16) AS CC, sum(UNIFICAVALOR) AS VALOR
FROM FatoFechamento WHERE YEAR(DATA) = 2025 AND TIPO = 'DESPESA'
GROUP BY DATA,RIGHT(CODGERENCIAL,16)

ORDER BY DATA,RIGHT(CODGERENCIAL,16) DESC